site_name: Signal RAG Bot Documentation
site_description: Production-ready Signal chatbot with RAG using FAISS vector store
site_author: Signal RAG Bot Team
site_url: https://github.com/BramAlkema/signal-rag-bot

# Repository
repo_name: BramAlkema/signal-rag-bot
repo_url: https://github.com/BramAlkema/signal-rag-bot
edit_uri: edit/main/docs/docs/

# Copyright
copyright: Copyright &copy; 2025 Signal RAG Bot

# Configuration
theme:
  name: material
  language: en
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mermaid2
  - mkdocstrings:
      handlers:
        python:
          paths: [..]
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            separate_signature: true

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started/overview.md
    - Quick Start: getting-started/quickstart.md
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
  - Deployment:
    - Docker Deployment: deployment/docker.md
    - Docker Compose: deployment/docker-compose.md
    - Docker Secrets: deployment/secrets.md
    - VPS Deployment: deployment/vps.md
    - Cloud Deployment: deployment/cloud.md
  - User Guide:
    - How to Use: user-guide/usage.md
    - Activation: user-guide/activation.md
    - Querying: user-guide/querying.md
    - Commands: user-guide/commands.md
  - Architecture:
    - System Overview: architecture/overview.md
    - Components: architecture/components.md
    - Data Flow: architecture/data-flow.md
    - RAG Pipeline: architecture/rag-pipeline.md
  - Security:
    - Security Overview: security/overview.md
    - Input Validation: security/input-validation.md
    - Rate Limiting: security/rate-limiting.md
    - Threat Detection: security/threat-detection.md
    - Best Practices: security/best-practices.md
  - Operations:
    - Monitoring: operations/monitoring.md
    - Logging: operations/logging.md
    - Health Checks: operations/health-checks.md
    - Troubleshooting: operations/troubleshooting.md
    - Backup & Restore: operations/backup-restore.md
  - API Reference:
    - Custom RAG: api/custom-rag.md
    - Security: api/security.md
    - Error Handling: api/error-handling.md
    - Monitoring: api/monitoring.md
  - Development:
    - Setup: development/setup.md
    - Testing: development/testing.md
    - Contributing: development/contributing.md
    - Code Style: development/code-style.md
  - Reference:
    - Environment Variables: reference/environment.md
    - Docker Configuration: reference/docker.md
    - FAQ: reference/faq.md
    - Changelog: reference/changelog.md

# Extra
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/BramAlkema/signal-rag-bot
  generator: false

# Extra CSS
extra_css:
  - stylesheets/extra.css
